Repository Heresta/BAO_Stage_DH_ENS_2021, pull requests merged in 2021-04, with the labels that each got.

#4 Création README pour Correction PAGE XML
  Boite_a_outils/CorrectionPageXMLeScriptorium/README.md
Labels: documentation

#5 Creation document compréhension format ALTO4
  Boite_a_outils/documentationFormatsExistants/doc_comprehension_ALTO2.xml
  Boite_a_outils/documentationFormatsExistants/doc_comprehension_ALTO4.xml
  Boite_a_outils/documentationFormatsExistants/doc_comprehension_PageXML_sortieTranskribus.xml
  Boite_a_outils/documentationFormatsExistants/doc_comprehension_PageXML_sortieeScriptorium.xml
Labels: documentation

#6 Création du README principal
  README.md
Labels: documentation

#7 Ajout automatique des lignes defaults
  Boite_a_outils/CorrectionPageXMLeScriptorium/README.md
  Boite_a_outils/CorrectionPageXMLeScriptorium/migrationCorrection.xsl
Labels: XSLT, documentation, migration

#9 MAJ du README.md
  README.md
Labels: documentation

#10 Création doc dossier problemesSegmentation
  README.md
  problemesSegmentation/README.md
  problemesSegmentation/img/1856_10_LAV_N03-1.png
  problemesSegmentation/img/1887_bovet_bpt6k6325943w_gt_0076.jpg.png
  problemesSegmentation/img/Cat_Venezia_1920_typo_0005.jpg
  problemesSegmentation/img/page_ acteurs_prologue_Boyer_Meduse_1697.png
  problemesSegmentation/img/page_1_catalogue_lettres_autographes_1845.png
  problemesSegmentation/img/page_ordre_vacation_catalogue_lettres_autographes_1845.png
  problemesSegmentation/img/page_prologue_Boyer_Meduse_1697.png
  problemesSegmentation/img/page_titre_Boyer_Meduse_1697.png
  problemesSegmentation/img/page_titre_Moliere_Escole_des_Maris_1661.png
  problemesSegmentation/img/page_titre_catalogue_lettres_autographes_1845.png
  problemesSegmentation/img/part_page_ 11_Boyer_Meduse_1697.png
  problemesSegmentation/img/part_page_ acteurs_prologue_Boyer_Meduse_1697.png
  problemesSegmentation/img/part_page_acteurs_Boyer_Meduse_1697.png
  problemesSegmentation/recap_problemes.csv
Labels: documentation

#11 Ajout pb seg
  problemesSegmentation/img/page_12_Descartes_Discours_Methode_1637.png
  problemesSegmentation/img/page_IX_Corneille_Théâtre_P_Corneille_1661.png
  problemesSegmentation/recap_problemes.csv
Labels: documentation

#12 Update README.md
  README.md
Labels: documentation

#13 Ajout deux fichiers python
  Automatisation_copie_fichiers/README.md
  Automatisation_copie_fichiers/copie_fichiers_xml.py
  Automatisation_copie_fichiers/fichier_hasard.py
  README.md
Labels: python

#15 Retrait transcription de fichiers xml
  README.md
  RetraitTranscriptionPAGEXML/README.md
  RetraitTranscriptionPAGEXML/arrivee.xml
  RetraitTranscriptionPAGEXML/depart.xml
  RetraitTranscriptionPAGEXML/retrait_transcription.xsl
  RetraitTranscriptionPAGEXML/xml_segment_only.py
Labels: XSLT, python

#14 MAJ README
  CorrectionPageXMLeScriptorium/README.md
Labels: documentation
